#!/data/data/com.termux/files/usr/bin/bash
if (($#==1));
then
	case $(uname -m) in
		arm*) LIBPATH=/system/lib;;
		aarch64*) LIBPATH=/system/lib64;;
	esac
LD_LIBRARY_PATH=$LIBPATH:$LD_LIBRARY_PATH
./openslplay $@
else
echo "Usage: execplay <filepath>"
fi
